MGMT-14787: Adding tests for events pagination WIP
openshift-assisted/assisted-installer-ui pull request #2193
Opened 2023-06-09 12:53 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-14787

2023-06-19 12:54 UTC, jkilzi requested changes

2023-06-19 12:54 UTC, jkilzi commented on libs/ui-lib-tests/cypress/views/pages/ClusterPage.ts
> +  }
```suggestion
  static visit(clusterId = Cypress.env('clusterId'), options?: Partial<Cypress.VisitOptions>) {
    return cy.visit(`/clusters/${clusterId}`, options);
  }
```

2023-06-19 12:54 UTC, jkilzi commented on libs/ui-lib-tests/cypress/views/modals/eventsModal.ts
> +export default class EventsModal {
Sorry, after thinking about this again we might hit a cyclic dependency problem due to having the EventsModal importing the ClusterPage.

The EventsModal (and all of its parts) appear not only in the ClusterPage, so imagine you would like to add a test for the installation page. Given the way this "page-object" is written the installation page will transitively import the cluster page (now what have both to do with each other if the test we are writing is only concerned about the events modal)

2023-06-19 12:54 UTC, jkilzi commented on libs/ui-lib-tests/cypress/views/modals/eventsModal.ts
> +export default class EventsModal {
Let's sync on this I think I have a better solution

2023-06-20 14:23 UTC, ammont82 commented on libs/ui-lib-tests/cypress/fixtures/cluster/events.ts
> +const clusterEvents = [
I agree with @jkilzi . Maybe you can implement a function to make events.

2023-06-22 09:31 UTC, ammont82 submitted a review, later dismissed

2023-06-22 09:58 UTC, ammont82 approved these changes

2023-06-22 11:54 UTC, jkilzi approved these changes

2023-06-22 11:54 UTC, merged