ACM-13728: Missing s390x arch option in Cpu architecture in InfraEnv
openshift-assisted/assisted-installer-ui pull request #2668
Opened 2024-09-24 13:00 UTC by jgyselov

https://issues.redhat.com/browse/ACM-13728

Console PR: https://github.com/stolostron/console/pull/3894

2024-10-07 07:13 UTC, rawagner requested changes

2024-10-07 07:13 UTC, rawagner commented on libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
> +  }, [cpuArchOpen]);
There is no need to memoize this function. It could also be simplified to `setCpuArchOpen(!cpuArchOpen)`

2024-10-07 07:13 UTC, rawagner commented on libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
> +
Again, no need to memoize. 

There is also a bug in formik, where `setFieldValue` is always a new instance - we have a workaround for that in [useFormikHelpers.ts](https://github.com/openshift-assisted/assisted-installer-ui/blob/master/libs/ui-lib/lib/common/hooks/useFormikHelpers.ts)

We can also simplify `setFieldValue('userManagedNetworking', val === CpuArchitecture.s390x);`

2024-10-11 04:59 UTC, ammont82 approved these changes

2024-10-11 07:05 UTC, rawagner approved these changes

2024-10-11 07:06 UTC, merged